# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pustaka', '0004_jeniskelamin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pekerjaan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pekerjaan', models.CharField(max_length=75)),
                ('tipe', models.CharField(choices=[('A', 'PNS dan Mandiri'), ('B', 'Sebaliknya')], max_length=1)),
            ],
        ),
    ]
