# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pustaka', '0005_pekerjaan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pekerjaan',
            name='tipe',
            field=models.CharField(choices=[('A', 'A untuk PNS dan Mandiri'), ('B', 'B untuk Sebaliknya')], max_length=1),
        ),
    ]
