# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pustaka', '0009_statuskawin'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusKependudukan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_kependudukan', models.CharField(max_length=45)),
            ],
        ),
    ]
