# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pustaka', '0010_statuskependudukan'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusKk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_kk', models.CharField(max_length=64)),
            ],
        ),
    ]
