# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pustaka', '0012_statustinggal'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibSurat',
            fields=[
                ('kode_surat', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('nama_surat', models.CharField(max_length=200)),
                ('parent_id', models.CharField(max_length=45)),
            ],
        ),
    ]
