# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penduduk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='penduduk',
            name='tanggal_lahir',
            field=models.DateField(null=True),
        ),
    ]
