# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pengaturan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_desa', models.CharField(max_length=100)),
                ('kode_desa', models.CharField(max_length=100)),
                ('nama_kepala_desa', models.CharField(max_length=100)),
                ('nip_kepala_desa', models.CharField(max_length=100)),
                ('kodepos', models.CharField(max_length=6)),
                ('nama_kecamatan', models.CharField(max_length=100)),
                ('kode_kecamatan', models.CharField(max_length=100)),
                ('nama_kepala_camat', models.CharField(max_length=100)),
                ('nip_kepala_camat', models.CharField(max_length=100)),
                ('nama_kabupaten', models.CharField(max_length=100)),
                ('kode_kabupaten', models.CharField(max_length=100)),
                ('nama_provinsi', models.CharField(max_length=100)),
                ('kode_provinsi', models.CharField(max_length=100)),
                ('logo_desa', models.CharField(max_length=100)),
                ('logo_kabupaten', models.CharField(max_length=100)),
                ('alamat_kantor_desa', models.CharField(max_length=100)),
            ],
        ),
    ]
