# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 23:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pengaturan_umum', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pengaturan',
            new_name='PengaturanUmum',
        ),
    ]
