# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 03:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pengaturan_umum', '0002_auto_20161223_0609'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PengaturanUmum',
            new_name='IdentitasDesa',
        ),
    ]
