# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('penduduk', '0001_initial'),
        ('pustaka', '0014_jabatanperangkat'),
        ('pengaturan_umum', '0003_auto_20161223_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerangkatDesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niap', models.CharField(max_length=45)),
                ('nip', models.CharField(max_length=45)),
                ('pangkat_golongan', models.CharField(max_length=45)),
                ('no_tanggal_keputusan_pengangkatan', models.CharField(max_length=45)),
                ('no_tanggal_keputusan_pemberhentian', models.CharField(max_length=45)),
                ('keterangan', models.TextField()),
                ('nama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='penduduk.Penduduk')),
                ('nama_jabatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pustaka.JabatanPerangkat')),
            ],
        ),
    ]
